services:
mariadb:
	container_name: mariadb
	build: ./requirements/mariadb
	image: mariadb
	env_file: .env
	networks: inception-network
	volumes: mariadb_data:/var/lib/mysql
	secrets:
	- db_password
	- db_root_password
	restart: unless-stopped

wordpress:
	container_name: wordpress
	build: ./requirements/wordpress
	image: wordpress
	volumes: wordpress_data:/var/www/html
	networks: inception-network
	env_file: .env
	secrets:
	- db_password
	- wp_user_password
	- wp_admin_password
	restart: unless-stopped
	depends_on: mariadb

nginx:
	container_name: nginx
	build: ./requirements/nginx
	image: nginx
	ports: 443:443
	volumes: -wordpress_data:/var/www/html
	networks: inception-network
	env_file: .env
	restart: unless-stopped
	depends_on: wordpress

networks:
	inception-network:
	name: inception-network
	driver: bridge

volumes:
	mariadb_data:
	driver: local
	driver_opts:
		type: none
		device: $HOME/data/mariadb
		o: bind
	
	wordpress_data:
	driver: local
	driver_opts:
		type: none
		device: $HOME/data/wordpress
		o: bind
	
	secrets:
		db_password:
		file: ../secrets/db_password

		db_root_password:
		file: ../secrets/db_root_password

		wp_user_password:
		file: ../secrets/wp_user_password

		wp_admin_password:
		file: ../secrets/wp_admin_password
